name: miio_new
description: Dart implementation of MiIO LAN protocol for smart home devices.
version: 1.0.1
homepage: https://github.com/ctrysbita/miio.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.6.0
  convert: ^3.1.2
  crypto: ^3.0.6
  cryptography: ^2.7.0
  json_annotation: ^4.9.0
  logger: ^2.4.0 # For CLI only.
  logging: ^1.3.0
  meta: ^1.16.0
  quiver: ^3.2.2
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  lints: ^5.0.0

